version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-pterodactyl-test
    ports:
      - "5678:5678"
    environment:
      - N8N_CUSTOM_EXTENSIONS=/data/custom
      - N8N_LOG_LEVEL=debug
      - N8N_LOG_OUTPUT=console
      - GENERIC_TIMEZONE=UTC
      - TZ=UTC
    volumes:
      # Mount the built node files
      - ./dist:/data/custom/n8n-nodes-pterodactyl/dist:ro
      - ./package.json:/data/custom/n8n-nodes-pterodactyl/package.json:ro
      # Persistent data
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  n8n_data:
    driver: local
